// Germany Political System Data
// Design: Prussian Blue × Amber Gold × Deep Charcoal
// Typography: Space Grotesk (headings) + Noto Serif SC (body)

export const deStats = [
  { label: "联邦州数量", value: 16, suffix: "个", color: "#D4A017" },
  { label: "联邦议院席位", value: 630, suffix: "席", color: "#4A90D9" },
  { label: "选民人数", value: 6100, suffix: "万", color: "#5BAD6F" },
  { label: "政党5%门槛", value: 5, suffix: "%", color: "#E07B54" },
  { label: "联邦总统任期", value: 5, suffix: "年", color: "#9B7FD4" },
  { label: "宪法法院法官", value: 16, suffix: "名", color: "#4A90D9" },
];

export const deInstitutions = [
  {
    id: "bundestag",
    name: "联邦议院",
    germanName: "Bundestag",
    icon: "🏛️",
    color: "#4A90D9",
    seats: 630,
    term: "4年",
    description: "德国最高立法机关，由全体选民直接选举产生。负责制定联邦法律、选举联邦总理、监督政府、批准国家预算。",
    powers: [
      "制定和修改联邦法律",
      "选举联邦总理（需绝对多数）",
      "监督联邦政府施政",
      "批准联邦预算",
      "通过建设性不信任投票罢免总理",
      "批准国际条约",
    ],
    details: "联邦议院设有常设委员会，负责审查各领域法案。议员按党团组织，党团须有至少5%议员方可成立。议长由最大党提名，现任议长为尤利娅·克勒克纳（基民盟）。",
  },
  {
    id: "bundesrat",
    name: "联邦参议院",
    germanName: "Bundesrat",
    icon: "🗺️",
    color: "#D4A017",
    seats: 69,
    term: "无固定任期",
    description: "代表16个联邦州参与联邦立法，由各州政府成员组成（非直选）。按各州人口分配3-6票。",
    powers: [
      "参与联邦立法（同意权或异议权）",
      "对涉及州权利的法案有绝对否决权",
      "对其他法案有延迟否决权（可被联邦议院推翻）",
      "选举联邦宪法法院8名法官",
      "议长代行联邦总统职务",
    ],
    details: "各州票数：人口200万以下3票，200-600万4票，600-700万5票，700万以上6票。各州须整体投票，不可分裂。议长由各州州长轮任，任期一年。",
  },
  {
    id: "bundespraesident",
    name: "联邦总统",
    germanName: "Bundespräsident",
    icon: "🦅",
    color: "#5BAD6F",
    seats: 1,
    term: "5年（最多连任一届）",
    description: "国家元首，礼仪性职务。由联邦大会（联邦议院全体议员+等数量各州代表）选举产生。",
    powers: [
      "签署并颁布联邦法律（可拒绝签署违宪法律）",
      "形式上任命联邦总理",
      "形式上任命和免除联邦部长",
      "代表国家对外",
      "授予赦免权",
      "在政府危机时解散联邦议院",
    ],
    details: "现任总统：弗兰克-瓦尔特·施泰因迈尔（社民党）。联邦大会由联邦议院全体议员和各州议会选出的等数量代表组成，专门用于选举总统，选后即解散。",
  },
  {
    id: "bundeskanzler",
    name: "联邦总理",
    germanName: "Bundeskanzler",
    icon: "⚖️",
    color: "#E07B54",
    seats: 1,
    term: "4年（与联邦议院同期）",
    description: "政府首脑，掌握最高行政权力。由联邦议院选举产生，须获得绝对多数（316票以上）。",
    powers: [
      "确定政府政策方针（Richtlinienkompetenz）",
      "任命和免除联邦部长",
      "主持联邦政府会议",
      "统率联邦武装力量（战时）",
      "提请联邦总统解散联邦议院",
      "代表政府对外",
    ],
    details: "现任总理：弗里德里希·默茨（基民盟，2025年5月起）。德国总理权力极大，可自行决定内阁人选。只能通过'建设性不信任投票'被罢免，即同时须选出继任者，防止政府真空。",
  },
  {
    id: "bundesverfassungsgericht",
    name: "联邦宪法法院",
    germanName: "Bundesverfassungsgericht",
    icon: "⚖️",
    color: "#9B7FD4",
    seats: 16,
    term: "12年（不可连任）",
    description: "德国最高司法机关，位于卡尔斯鲁厄。负责监督《基本法》的遵守，所有国家机关均受其约束。",
    powers: [
      "违宪立法审查（抽象审查和具体审查）",
      "裁决宪法机关间的权力争议",
      "裁决联邦与州之间的权力争议",
      "审查政党是否违宪（可禁止政党）",
      "受理公民宪法诉愿",
      "审查选举结果",
    ],
    details: "分为两个参议庭，各8名法官。8名由联邦议院选出，8名由联邦参议院选出，均须获得2/3多数。历史上曾禁止两个政党（1952年新纳粹党，1956年共产党）。",
  },
];

export const deElectionSystem = {
  title: "两票混合比例代表制",
  description: "德国选举制度兼顾直接民主（第一票）与比例代表（第二票），是世界上最复杂也最公平的选举制度之一。",
  votes: [
    {
      name: "第一票",
      germanName: "Erststimme",
      color: "#4A90D9",
      seats: 299,
      method: "相对多数制",
      description: "投给本选区的直接候选人。全国299个选区，每区选出1名议员，得票最多者当选（不需要过半数）。",
      effect: "确保每个选区都有直接代表，增强议员与选区的联系。",
    },
    {
      name: "第二票",
      germanName: "Zweitstimme",
      color: "#D4A017",
      seats: 331,
      method: "比例代表制",
      description: "投给政党。决定各政党在联邦议院的总席位比例。政党须获得至少5%第二票（或在3个选区直接当选）才能进入议院。",
      effect: "决定政党实力，是最重要的一票。补偿席位确保议院整体比例与第二票结果一致。",
    },
  ],
  threshold: {
    percent: 5,
    exception: "若政党在至少3个选区直接当选，即使未达5%门槛，也可按比例获得席位",
    minority: "被认可的少数民族政党（如丹麦族SSW）不受5%门槛限制",
  },
  reform2025: "2025年改革：联邦议院固定630席，取消超额席位和补偿席位，若直选议员超出比例分配，部分直选议员将不能进入议院（按得票率最低者排除）。",
};

export const deParties = [
  {
    name: "基民盟/基社盟",
    abbr: "CDU/CSU",
    color: "#1a1a1a",
    bgColor: "#333333",
    ideology: "保守主义、基督教民主",
    founded: 1945,
    seats2025: 328,
    description: "德国最大保守主义政党，基民盟在全国运作，基社盟仅在巴伐利亚州。两党在联邦议院组成共同党团。",
    positions: ["市场经济", "欧洲一体化", "传统价值观", "强化国防"],
    leaders: ["弗里德里希·默茨（现任联邦总理）"],
  },
  {
    name: "社会民主党",
    abbr: "SPD",
    color: "#E3000F",
    bgColor: "#8B0000",
    ideology: "社会民主主义、中左",
    founded: 1863,
    seats2025: 120,
    description: "德国历史最悠久的政党之一，代表劳工阶层利益，支持福利国家和社会公平。",
    positions: ["最低工资", "社会保障", "气候保护", "欧洲团结"],
    leaders: ["奥拉夫·朔尔茨（前总理）"],
  },
  {
    name: "绿党",
    abbr: "Grüne",
    color: "#46962b",
    bgColor: "#2d5c1a",
    ideology: "绿色政治、社会自由主义",
    founded: 1980,
    seats2025: 85,
    description: "从环保运动发展而来，现已成为主流政党，关注气候变化、可再生能源和社会公正。",
    positions: ["气候中和", "可再生能源", "多元文化", "欧洲联邦"],
    leaders: ["安娜莱娜·贝尔伯克", "罗伯特·哈贝克"],
  },
  {
    name: "自由民主党",
    abbr: "FDP",
    color: "#FFED00",
    bgColor: "#B8A800",
    ideology: "古典自由主义、中右",
    founded: 1948,
    seats2025: 0,
    description: "代表商界和自由职业者利益，强调个人自由、市场经济和减少政府干预。2025年大选未过5%门槛。",
    positions: ["减税", "数字化", "个人自由", "欧洲改革"],
    leaders: ["克里斯蒂安·林德纳"],
  },
  {
    name: "德国另类选择党",
    abbr: "AfD",
    color: "#009EE0",
    bgColor: "#006B99",
    ideology: "右翼民粹主义、民族保守主义",
    founded: 2013,
    seats2025: 152,
    description: "2013年成立，以反欧元、反移民立场崛起，现为联邦议院第二大党。部分州级组织被列为极右翼监控对象。",
    positions: ["限制移民", "退出欧元区", "民族认同", "反建制"],
    leaders: ["爱丽丝·魏德尔"],
  },
  {
    name: "德国心脏党",
    abbr: "BSW",
    color: "#8B1A1A",
    bgColor: "#5C1111",
    ideology: "左翼民粹主义",
    founded: 2024,
    seats2025: 8,
    description: "由前左翼党领袖萨拉·瓦根克内希特创立，融合左翼经济政策与保守社会立场，反对对乌军援。",
    positions: ["反对军援乌克兰", "限制移民", "社会公平", "反美"],
    leaders: ["萨拉·瓦根克内希特"],
  },
];

export const deFederalism = [
  { state: "北莱茵-威斯特法伦", capital: "杜塞尔多夫", population: "1800万", votes: 6, color: "#4A90D9" },
  { state: "巴伐利亚", capital: "慕尼黑", population: "1300万", votes: 6, color: "#D4A017" },
  { state: "巴登-符腾堡", capital: "斯图加特", population: "1100万", votes: 6, color: "#5BAD6F" },
  { state: "下萨克森", capital: "汉诺威", population: "800万", votes: 6, color: "#9B7FD4" },
  { state: "黑森", capital: "威斯巴登", population: "630万", votes: 5, color: "#E07B54" },
  { state: "萨克森", capital: "德累斯顿", population: "400万", votes: 4, color: "#4A90D9" },
  { state: "莱茵兰-普法尔茨", capital: "美因茨", population: "410万", votes: 4, color: "#D4A017" },
  { state: "柏林", capital: "柏林", population: "380万", votes: 4, color: "#5BAD6F" },
  { state: "石勒苏益格-荷尔斯泰因", capital: "基尔", population: "290万", votes: 4, color: "#9B7FD4" },
  { state: "勃兰登堡", capital: "波茨坦", population: "260万", votes: 4, color: "#E07B54" },
  { state: "萨克森-安哈尔特", capital: "马格德堡", population: "220万", votes: 4, color: "#4A90D9" },
  { state: "图林根", capital: "埃尔福特", population: "210万", votes: 4, color: "#D4A017" },
  { state: "汉堡", capital: "汉堡", population: "180万", votes: 3, color: "#5BAD6F" },
  { state: "梅克伦堡-前波美拉尼亚", capital: "什未林", population: "160万", votes: 3, color: "#9B7FD4" },
  { state: "萨尔兰", capital: "萨尔布吕肯", population: "100万", votes: 3, color: "#E07B54" },
  { state: "不来梅", capital: "不来梅", population: "68万", votes: 3, color: "#4A90D9" },
];

export const deConstructiveVote = {
  title: "建设性不信任投票",
  germanName: "Konstruktives Misstrauensvotum",
  description: "德国《基本法》第67条规定的独特制度：联邦议院只能通过同时选出新总理的方式罢免现任总理，防止政治真空。",
  steps: [
    { step: 1, title: "提出动议", desc: "至少1/4联邦议院议员联署，提出不信任动议，同时提名新总理候选人" },
    { step: 2, title: "等待期", desc: "动议提出后须等待48小时方可投票，给各方谈判时间" },
    { step: 3, title: "投票", desc: "联邦议院投票，新总理候选人须获得绝对多数（316票以上）" },
    { step: 4, title: "结果", desc: "若通过：现任总理被罢免，新总理同时就职。若未通过：现任总理继续执政" },
  ],
  history: [
    { year: 1972, result: "失败", desc: "反对党试图以拉尔·巴泽尔取代维利·勃兰特，以2票之差失败" },
    { year: 1982, result: "成功", desc: "赫尔穆特·科尔（基民盟）取代赫尔穆特·施密特（社民党），德国历史上唯一一次成功案例" },
  ],
};

export const deCoalitions = [
  {
    name: "大联合政府",
    abbr: "GroKo",
    parties: ["CDU/CSU", "SPD"],
    years: "2005-2009, 2013-2017, 2018-2021",
    color: "#8B0000",
    description: "两大党联合，政治稳定但缺乏对立，常被批评削弱民主活力",
  },
  {
    name: "红绿灯联合",
    abbr: "Ampelkoalition",
    parties: ["SPD", "Grüne", "FDP"],
    years: "2021-2024",
    color: "#E3000F",
    description: "朔尔茨领导的三党联合，因FDP退出于2024年11月提前解散",
  },
  {
    name: "黑红联合",
    abbr: "Schwarz-Rot",
    parties: ["CDU/CSU", "SPD"],
    years: "2025-",
    color: "#1a1a1a",
    description: "默茨领导的新一届联合政府，2025年大选后组建",
  },
];

export const deSections = [
  { id: "intro", title: "立国基石", subtitle: "《基本法》与联邦制" },
  { id: "institutions", title: "五大机构", subtitle: "权力架构全解" },
  { id: "chancellor", title: "联邦总理", subtitle: "政府核心权力" },
  { id: "election", title: "选举制度", subtitle: "两票混合比例制" },
  { id: "parties", title: "政党格局", subtitle: "主要政党与立场" },
  { id: "coalition", title: "联合政府", subtitle: "组阁谈判机制" },
  { id: "federalism", title: "联邦制度", subtitle: "16州权力分配" },
  { id: "constructive", title: "建设性不信任", subtitle: "独特的倒阁制度" },
  { id: "judiciary", title: "司法体系", subtitle: "宪法法院与法治" },
  { id: "comparison", title: "制度对比", subtitle: "与其他民主国家比较" },
];
